Adds native metadata parsing for base metadata
PrismarineJS/prismarine-entity pull request #17
Opened 2021-02-10 02:34 UTC by u9g

adds a breaking change to the library

2021-02-10 02:34 UTC, u9g commented
Sources: 
- old data: https://wiki.vg/index.php?title=Entity_metadata&oldid=7415#Entity
- new data: https://wiki.vg/Entity_metadata#Entity_Metadata_Format

2021-02-10 02:51 UTC, extremeheat commented
This is something that should go into the protocol definition, but I think the version loader is a good idea

2021-02-10 05:31 UTC, u9g commented
starts to address https://github.com/PrismarineJS/mineflayer/issues/1263

2021-02-10 07:19 UTC, extremeheat reviewed
Ah, I see what's going on. It looks way more complicated in the protocol than it needs to be, so yeah I think it makes sense to do it here.

2021-02-10 07:19 UTC, extremeheat commented on index.js
> +  this.isOnFire = () => Boolean(this.metadata[0] & 0x01)
to be complete, can you add setting too?

2021-02-10 07:20 UTC, extremeheat commented on index.js
> +  this.isOnFire = () => Boolean(this.metadata[0] & 0x01)
would be a good idea to turn this to a class

2021-02-13 15:38 UTC, rom1504 requested changes
How did you check this works for most versions ? Any idea how to automatically test it ?

2021-02-28 13:58 UTC, TheDudeFromCI commented
You can probably do an easy test by running a mineflayer instance on a flat world server. Doing things like spawning an entity, setting them on fire, and seeing if the `isOnFire()` function returns true.

2021-02-28 16:11 UTC, u9g commented
The reason this is being slowed down isnt because we didnt have a way to test it, i was going to get the info from burger, just havent got around to usung burger once yet

2021-09-24 01:05 UTC, u9g commented
should be done using data from mcData

2021-09-24 01:05 UTC, closed without merging